import Head from "next/head";
import Link from "next/link";
import { useReducer, useContext } from "react";
import { TodoContext } from "@/state";
import Navbar from "@/components/navbar";
import TodoList from "@/components/todoList";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const { state } = useContext(TodoContext);
  return (
    <>
      <Head>
        <title>Next Global State - ToDoApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      {state.username ? (
        <main className={`${styles.Home}`}>
          <TodoList />
        </main>
      ) : (
        <div className={styles.login}>
          <h1>Per favore autenticarsi</h1>
          <Link href="/login">Login</Link>
        </div>
      )}
    </>
  );
}

export async function getServerSideProps(context) {
  return {
    props: {},
  };
}
