import Head from "next/head";
import TodoList from "@/components/todoList";
import Navbar from "@/components/navbar";
import { todomock } from "@/helpers/todomock";
import { useReducer } from "react";
import { TodoContext } from "@/state";
import { TodoReducer } from "@/state/reducers";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const [state, dispatch] = useReducer(TodoReducer, todomock);
  return (
    <>
      <Head>
        <title>Next Global State - ToDoApp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TodoContext.Provider value={{ state, dispatch }}>
        <main className={styles.Home}>
          <Navbar />
          <TodoList />
        </main>
      </TodoContext.Provider>
    </>
  );
}
